apiVersion: batch/v1
kind: Job
metadata:
  name: bb-movie-char-job
spec:
  template:
    spec:
      containers:
      - name: bb-movie-char-job
        image: yash5090/bb-movie-char:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
